- hosts: k8s_nodes
  become: yes
  tasks:
    - name: Ajouter le repo Helm officiel pour Nginx
      shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update

    - name: Installer NGINX Ingress Controller via Helm
      shell: |
        helm install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx \
          --create-namespace \
          --set controller.publishService.enabled=true

    - name: Vérifier que le NGINX Controller est déployé
      shell: kubectl rollout status deployment ingress-nginx-controller -n ingress-nginx
