apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modern-infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/modern-infra.git
    targetRevision: HEAD
    path: gitops/repo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true